version: '3.3'

services:
  app:
    build:
      context: .
    ports:
      - '8100:8100'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ionic serve --host 0.0.0.0 --port 8100


